/**
 * Configuration for each import type:
 * - targetFields: the fields we want to extract
 * - autoMap: attempt to auto-detect file headers → target fields
 * - dateField: which target field contains the date (for month detection)
 */

export const IMPORT_CONFIGS = {
  sumup_sales: {
    label: "SumUp Sales Report",
    description: "Export from SumUp → Reports → Sales",
    targetFields: [
      { key: "transaction_id", label: "Transaction ID" },
      { key: "date", label: "Date", required: true },
      { key: "payment_method", label: "Payment Method" },
      { key: "gross_inc_vat", label: "Gross Amount (inc VAT)" },
      { key: "vat", label: "VAT Amount" },
      { key: "net_ex_vat", label: "Net Amount (ex VAT)" },
      { key: "discount", label: "Discount" },
      { key: "currency", label: "Currency" },
      { key: "order_id", label: "Order ID" },
    ],
    dateField: "date",
    autoMap: {
      "transaction id": "transaction_id",
      "id": "transaction_id",
      "date": "date",
      "datum": "date",
      "payment method": "payment_method",
      "zahlungsmethode": "payment_method",
      "methode": "payment_method",
      "total": "gross_inc_vat",
      "gross": "gross_inc_vat",
      "total (eur)": "gross_inc_vat",
      "total eur": "gross_inc_vat",
      "brutto": "gross_inc_vat",
      "vat": "vat",
      "mwst": "vat",
      "tax amount": "vat",
      "net": "net_ex_vat",
      "net (eur)": "net_ex_vat",
      "netto": "net_ex_vat",
      "discount": "discount",
      "currency": "currency",
      "order id": "order_id",
    },
  },

  sumup_articles: {
    label: "SumUp Article Report",
    description: "Export from SumUp → Reports → Items / Articles",
    targetFields: [
      { key: "date", label: "Date", required: true },
      { key: "transaction_id", label: "Transaction ID" },
      { key: "product", label: "Product Name", required: true },
      { key: "sku", label: "SKU" },
      { key: "qty", label: "Quantity" },
      { key: "gross_inc_vat", label: "Gross Price (inc VAT)" },
      { key: "net_ex_vat", label: "Net Price (ex VAT)" },
      { key: "vat", label: "VAT" },
      { key: "vat_rate", label: "VAT Rate" },
      { key: "discount", label: "Discount" },
      { key: "payment_method", label: "Payment Method" },
    ],
    dateField: "date",
    autoMap: {
      "date": "date",
      "datum": "date",
      "transaction id": "transaction_id",
      "id": "transaction_id",
      "product": "product",
      "item": "product",
      "artikel": "product",
      "name": "product",
      "description": "product",
      "sku": "sku",
      "qty": "qty",
      "quantity": "qty",
      "anzahl": "qty",
      "menge": "qty",
      "price": "gross_inc_vat",
      "gross": "gross_inc_vat",
      "brutto": "gross_inc_vat",
      "net": "net_ex_vat",
      "netto": "net_ex_vat",
      "vat": "vat",
      "mwst": "vat",
      "vat rate": "vat_rate",
      "tax rate": "vat_rate",
      "discount": "discount",
      "payment method": "payment_method",
    },
  },

  sumup_transactions: {
    label: "SumUp Transaction Report",
    description: "Export from SumUp → Reports → Transactions / Payouts",
    targetFields: [
      { key: "date", label: "Date", required: true },
      { key: "transaction_id", label: "Transaction ID" },
      { key: "status", label: "Status" },
      { key: "payment_method", label: "Payment Type" },
      { key: "gross_inc_vat", label: "Amount" },
      { key: "net_ex_vat", label: "Net Amount" },
      { key: "vat", label: "Fee / VAT" },
    ],
    dateField: "date",
    autoMap: {
      "date": "date",
      "datum": "date",
      "transaction id": "transaction_id",
      "id": "transaction_id",
      "status": "status",
      "type": "payment_method",
      "payment type": "payment_method",
      "amount": "gross_inc_vat",
      "total": "gross_inc_vat",
      "net amount": "net_ex_vat",
      "fee": "vat",
    },
  },

  bank_transactions: {
    label: "Business Bank Transactions",
    description: "Export from your bank — CSV/Excel statement",
    targetFields: [
      { key: "date", label: "Date", required: true },
      { key: "counterparty", label: "Counterparty / Name", required: true },
      { key: "description", label: "Description / Reference" },
      { key: "amount_out", label: "Amount Out (debit)" },
      { key: "amount_in", label: "Amount In (credit)" },
      { key: "amount", label: "Amount (single column)" },
      { key: "balance", label: "Balance" },
    ],
    dateField: "date",
    autoMap: {
      "date": "date",
      "datum": "date",
      "valutadatum": "date",
      "buchungsdatum": "date",
      "counterparty": "counterparty",
      "name": "counterparty",
      "empfanger": "counterparty",
      "begunstigde": "counterparty",
      "tegenpartij": "counterparty",
      "description": "description",
      "omschrijving": "description",
      "verwendungszweck": "description",
      "reference": "description",
      "referentie": "description",
      "debit": "amount_out",
      "af": "amount_out",
      "bedrag af": "amount_out",
      "amount out": "amount_out",
      "credit": "amount_in",
      "bij": "amount_in",
      "bedrag bij": "amount_in",
      "amount in": "amount_in",
      "amount": "amount",
      "bedrag": "amount",
      "betrag": "amount",
      "balance": "balance",
      "saldo": "balance",
    },
  },

  supplier_documents: {
    label: "Supplier Documents",
    description: "Invoices or delivery notes from meat/product suppliers",
    targetFields: [
      { key: "date", label: "Date", required: true },
      { key: "supplier", label: "Supplier Name" },
      { key: "description", label: "Product / Description" },
      { key: "qty", label: "Quantity / Weight (kg)" },
      { key: "unit_price", label: "Unit Price / Price per kg" },
      { key: "amount", label: "Total Amount" },
      { key: "vat", label: "VAT" },
      { key: "invoice_number", label: "Invoice Number" },
    ],
    dateField: "date",
    autoMap: {
      "date": "date",
      "datum": "date",
      "supplier": "supplier",
      "leverancier": "supplier",
      "description": "description",
      "product": "description",
      "artikel": "description",
      "qty": "qty",
      "kg": "qty",
      "weight": "qty",
      "gewicht": "qty",
      "quantity": "qty",
      "unit price": "unit_price",
      "price per kg": "unit_price",
      "preis": "unit_price",
      "total": "amount",
      "amount": "amount",
      "bedrag": "amount",
      "vat": "vat",
      "mwst": "vat",
      "invoice": "invoice_number",
      "invoice number": "invoice_number",
      "factuurnummer": "invoice_number",
    },
  },

  logistics_documents: {
    label: "Logistics / Transport Documents",
    description: "Invoices from transport or logistics providers",
    targetFields: [
      { key: "date", label: "Date", required: true },
      { key: "provider", label: "Provider / Carrier" },
      { key: "description", label: "Description" },
      { key: "amount", label: "Total Amount" },
      { key: "vat", label: "VAT" },
      { key: "invoice_number", label: "Invoice / Reference Number" },
      { key: "tracking", label: "Tracking / Shipment ID" },
    ],
    dateField: "date",
    autoMap: {
      "date": "date",
      "datum": "date",
      "provider": "provider",
      "carrier": "provider",
      "vervoerder": "provider",
      "description": "description",
      "omschrijving": "description",
      "amount": "amount",
      "total": "amount",
      "bedrag": "amount",
      "vat": "vat",
      "mwst": "vat",
      "invoice": "invoice_number",
      "invoice number": "invoice_number",
      "reference": "invoice_number",
      "tracking": "tracking",
      "shipment id": "tracking",
    },
  },
};

/**
 * Auto-detect column mapping by matching file headers against autoMap dictionary
 */
export function autoDetectMapping(headers, importType) {
  const config = IMPORT_CONFIGS[importType];
  if (!config) return {};
  const mapping = {};
  for (const header of headers) {
    const key = header.toLowerCase().trim();
    if (config.autoMap[key]) {
      mapping[config.autoMap[key]] = header;
    }
  }
  return mapping;
}